<svelte:head>
  <title>Films québécois</title>
</svelte:head>

<div id="about-page" class="page-wrapper about-page content-page">
    <div class="content">
        <h1>FILMS QUÉBÉCOIS</h1>

        <p>Entre 2018 et la fin de 2020, malgré la pandémie, il y a eu un grand nombre de films québécois qui ont pu être visionnés, soit sur grand écran, soit à la maison.</p> 
<p>Le Movie Shrink a choisi de rendre compte de sept d’entre eux dans cette chronique du début de février 2021. </p>
<p>Il s’agit des films suivants : <b>Les nôtres</b> (2020), <b>Jusqu’au déclin</b> (2020), <b>La grande noirceur</b> (2020), <b>Jouliks</b> ( 2019), <b>Répertoire des villes disparues</b> (2019), <a href="/fr/post/antigone"><b>Antigone</b></a> ( 2019) et <b>Chiens de garde</b> (2018). </p>
<p>Avant de regarder quels sont les thèmes qui les animent, présentons brièvement un synopsis de chacun d’eux, au risque de raconter l’histoire à ceux qui voudraient regarder le film sans connaître des éléments de l’histoire. Pour ceux-là, on pourra sauter les descriptions de certains de films. </p>
<p><b>Les nôtres</b> (2020) raconte le lourd secret que porte une très jeune adolescente qui a été abusée par le maire très respecté d’une petite ville prospère. La jeune adolescente gardant le secret de  l’identité de celui qui l’a mises enceinte, les soupçons se portent sur un jeune immigrant qui demeure en réalité chez le maire lui-même, comme famille d’accueil. La fin du film n’est pas totalement claire, mais on en arrive à comprendre que la petite ville a continué son chemin, sans que le maire soit incommodé, même après que la DPJ ait signalé des éléments qui auraient pu l’incriminer.</p>
<p><b>Jusqu’au déclin</b> (2020) est un film qui a paru sur Netflix, et il a donc pu être vu par un très grand nombre de spectateurs. Il s’agit d’une histoire de personnes qui s’entraînent dans un camp en forêt comme groupe survivalistes durant un week-end, afin de pratiquer leurs talents de survivalistes pour le grand jour où cette retraite dans les bois sera rendue nécessaire à cause d’un désastre qui nous attend. La pratique du groupe tourne mal et plusieurs survivalistes ne survivent pas à l’expérience. </p>
<p><b>La grande noirceur</b> (2020) nous raconte les péripéties d’un Québécois qui fuit la conscription de la Deuxième guerre mondiale en s’exilant aux États-Unis en participant à des concours d’imitateurs de Charlie Chaplin. Les individus qu’il rencontre dans son parcours, que ce soit des Américains ou des Français se trouvant aux États-Unis à ce moment, abusent de lui de différentes façons, le laissant au final seul  dans sa recherche pour atteindre le domicile d’un oncle résident dans la région de Détroit.</p>
<p><b>Jouliks</b> (2019) nous présente une famille vivant à la façon de hippies des années 1970, avec un jeune père membre d’un groupe de <i>Jouliks</i>. Le père quitte à l’occasion la mère et la jeune fille pour visiter son groupe d’origine établi dans une sorte de repère de <i>gypsies</i> dans une zone délabrée aux confins de Toronto. La jeune fille, une enfant, emprisonne par mégarde ses parents dans un puits afin qu’ils puissent se réconcilier après le retour du père lors de sa dernière escapade chez les <i>Jouliks</i>. Une pluie diluvienne enferme les amants dans le puits, dans une fin tragique du film. </p>
<p><b>Répertoire des villes disparues</b> (2019) est probablement, parmi les films mentionnés ici, le plus proche de ce qu’on imagine être les films québécois d’il y a une décennie ou deux. Le film se déroule dans un petit bled où la mine, principal employeur des lieux, vient de fermer. Des apparitions viennent hanter le village, composées essentiellement, selon les experts consultés, des âmes de résidents qui sont décédés auparavant. Le film s’ouvrait sur le décès d’un jeune homme, suicidé, qui faisait partie des jeunes qui ne voyaient pas d’avenir dans le village. </p>
<p><a href="/fr/post/antigone"><b>Antigone</b></a> (2019) est un film qui a été proclamé meilleur film  canadien de 2019 au Festival de films de Toronto (TIFF). Ce film est analysé par le Movie Shrink dans sa section principale , consacrée aux films du monde. Il s’agit d’une famille d’émigrants venant d’Algérie, suite à un drame dans leur pays d’origine, composée d’une grand-mère et de ses quatre petits-enfants, deux gars et deux filles. Suite as des bavures policières dramatiques impliquant les deux frères, impliqués dans des gangs de rue, un des deux frères meurt et l’autre est mis sous arrêt. <a href="/fr/post/antigone"><b>Antigone</b></a>, la sœur ainée est prise dans un dilemme, comme dans la pièce de Sophocles du même nom ( <a href="/fr/post/antigone"><b>Antigone</b></a>) : tout faire pour  sauver son frère ou faire son chemin avec succès  dans son nouveau pays. </p>
<p><b>Chiens de garde</b> (2018), un peu à l’image du <b>Répertoire des villes disparues</b> (2019), ressemble, par certaines dimensions, à un film québécois d’il y a quelques décennies. Une famille composée d’une mère et deux fils se voient exploitée par un oncle mafieux qui demande aux fils d’exécuter des tâches criminelles, impliquant même des meurtres. L’ainé des fils se révolte et élimine l’oncle.</p>

<h1>LES INTERPRÉTATIONS DU MOVIE SHRINK</h1>

<p>Nous allons voir les interprétations du Movie Shrink en deux temps. D’abord, les éléments des films mentionnés qui semblent contemporains, modernes et qui témoignent des nouveaux thèmes du cinéma québécois, puis, dans un deuxième temps, les éléments plus traditionnels, que l’on retrouve dans plusieurs films québécois des décennies précédentes. Non pas, bien entendu, qu’il y ait cassure entre les deux, mais ce sont des points de départ. 
<p>Commençons par les thématiques plus récentes. Dans ces thématiques récentes, on s’attend un peu à ce que certaines d’entre elles rejoignent des thèmes universaux, ceux que l’on retrouve par exemple dans les films que le Movie Shrink analyse dans sa section principale, dans la section internationale. </p>
<p>Une première thématique semble ressortir est celle d’un certain vacuum institutionnel. En effet, on semble être devant plusieurs règles, plusieurs recommandations différentes, plusieurs conflits d’allégeance. Lesquelles choisir? <a href="/fr/post/antigone"><b>Antigone</b></a> est prise entre sa loyauté familiale et sa loyauté envers son pays d’adoption; ses jeunes frères, entre leur loyauté envers leurs frères des gangs de rue et leur loyauté envers leur famille. Pour le jeune père dans <b>Jouliks</b>, c’est le conflit entre son groupe d’origine et sa jeune famille. Dans <b>Chiens de garde</b>, le conflit entre la loyauté envers l’oncle et ses propres ambitions légitimes dans la société de droit. Sans compter l’imitateur de Charlie Chaplin, dans <b>La grande noirceur</b>, qui n’a pas le choix entre plusieurs allégeances, puisqu’il est dans un vacuum institutionnel complet. </p>
<p>Cette incertitude de repères ne va pas, à l’occasion, sans une certaine carence des institutions en place. Une carence qui tient parfois ses bases dans une certaine hypocrisie des institutions dominantes. C’est dans le film <b>Les nôtres</b> que cette composante de mensonges apparaît le plus clairement, dans un récit où le maire coupable se tire complètement d’affaire dans un milieu qui refuse de voir. Sous un autre angle, le récent <b>Everybody knows</b>, analysé dans notre section principale, fait le même constat. Ce thème des incertitudes institutionnelles est aussi abordé dans <b>First Cow</b>, relatant les débuts des institutions et des règles vis-à-vis du vol et du meurtre dans un Oregon du dix-huitième siècle. Ce dernier film fait aussi partie de nos films de la section principale.</p>
<p>Dans cette incertitude au niveau des règles et du comment-vivre, se trouve une authentique recherche de repères. Dans presque tous les films mentionnés, on trouve une recherche de recettes de morale ou de comment-vivre en groupe. Que certaines d’entre elles soient présentées de façon ironique ou comme étant de toute évidence fausses en dit déjà long sur le sujet. </p>
<p>Ainsi, dans <b>Jusqu’au déclin</b>, des gens qui ne se connaissaient pas avant la fin de semaine de l’exercice survivaliste sont invités à se solidariser à la vie, à la mort en cas d’attaques de la part de tiers dangereux. Dans Le <b>Répertoire des villes disparues</b>, La maîresse Smallwood fait appel à une incantation, à savoir qu’on « est tissés serrés ici », et qu’on est « tous ensemble » ici. Dans le même film, Le personnage de Louise trouve dans des notions de psychologie à bon marché, comme des « peurs irrationnelles », pour expliquer la situation précaire de certains personnages en crise. La petite héroïne dans <b>Jouliks</b> trouve des raisons d’être optimiste, malgré tout, par le fait de se tenir debout « toute seule » Toujours dans <b>Jouliks</b>, la mère de la jeune épouse considère que la mode de vie désorganisé des parents ne sont pas de bonne augure pour l’éducation de sa petite fille, des propos que l’on considère « vieux jeux » au moment où ils sont exprimés, mais qui ne paraissent pas si condamnables considérant la suite des choses dans la fin tragique du film. Dans <b>La grande noirceur</b>, les propos de la tortionnaire, à l’effet que le départ de son mari à la guerre lui a donné l’opportunité de la remplacer à l’usine et que cette opportunité était le signe du destin qui voulait que « good things happen to good people », une remarque ironique dans le contexte de pauvreté et de désorganisation du village où se déroule l’essentiel du film.   Mais la palme de ces éthiques de fortune revient aux propos de l’imitateur de Charlie Chaplin, dans le même <b>La grande noirceur</b>, qui déclare, dans l’ouverture du film, qu’il faut travailler entre humains et ne pas se détruire les uns les autres, puisqu’il « y avait de la place pour tout le monde ». Ceci, juste avant de se faire torturer régulièrement par ses semblables dans toute la suite du film. </p>
<p>Un autre thème, qu’on peut qualifier de moderne ou de contemporain, est celui de l’intensité. Ce thème peut paraître quelque peu abstrait, mais cela n’empêche pas de le trouver dans plusieurs films québécois, comme dans plusieurs films internationaux d’ailleurs. Nous reviendrons plus loin sur ses sources possibles. </p>
<p>C’est dans <b>Jusqu’au déclin</b>, qui raconte le week-end des candidats au survivalisme que ce thème de l’intensité apparaît le plus évident, puisque ses adeptes sont convaincus d’un grand danger, imminent, devant lequel il faut de protéger par tous les moyens. Bien entendu, comme dans presque tous les cas de forte intensité, les choses tournent mal. Vers la fin des tueries, Alain, le professeur du week end de survivalisme, après que la plupart des participants ont été tués, conclut, dans un <i>understatement</i> presque drôle : « C’est allé trop loin ». </p>
<p>Dans le même esprit, <a href="/fr/post/antigone"><b>Antigone</b></a>  et d’autres participants à la tragédie familiale, sont eux-aussi marqués d’une grande intensité, qui ne les mène pas toujours vers des jours meilleurs ou heureux. </p>
<p>Dans <b>Jouliks</b>, l’intensité du désir de la petite fille de voir ses parents se réconcilier par l’amour mène à la tragédie finale. </p>
<p>Ce traitement de l’intensité, vue comme un élément souvent déstabilisant, se retrouve aussi dans des films internationaux, du moins dans ceux que Le Movie Shrink a revu dans le cadre de sa section principale sur le films du monde. </p>
<p>Ainsi, <b>The Sound of Metal</b> fait état des péripéties d’un batteur heavy metal qui devient sourd à force de battre à l’extrême ses instruments de musique jour et nuit. Mais, bien entendu, il s’agit d’un cas aussi extrême qu’évident. </p>
<p>Paradoxalement, il se peut que ce soit dans des cas moins évidents que se révèle le plus les éléments sous-jacents de cette recrudescence de l’intensité. Des films internationaux, c’est-à-dire non québécois, pourraient mieux nous éclairer sur les sources de cette intensité. Ainsi , <b>The Vast of Night</b> et <b>A Beautiful day in the neighborhood</b>, chacun à leur façon, le premier en nous prévenant de dangers potentiels de nouveaux médias, le second en se rappelant d’un monde plus paisible, présenté à la télévision des années 1970, pourraient révéler, plus ou moins directement, les dérapages médiatiques des dernières décennies. </p>
<p>Comme dernier thème contemporain des films québécois des deux ou trois dernières années, se trouve le thème très contemporain de l’immigration. </p>
<p>Les angles par lesquels on regarde ce thème sont, au final, assez variés. </p>
<p>Il y a trois films québécois qui prennent fait et cause en faveur de la perspective des arrivants. </p>
<p><b>Les nôtres</b> lors duquel un jeune immigrant est soupçonné, à tort d’avoir mis enceinte une jeune adolescente, alors que c’est un des « nôtres », le maire des lieux, va dans le sens de nos impressions initiales sur les immigrants, qui peuvent se révéler non fondées. Au milieu du film, une voisine bien intentionnée, avait dit, à propos des jeunes immigrants, qu’ils « ne sont pas comme nous » et le maire, l’éventuel coupable, avait déclaré à propos des propres jeunes qu’il avait accueillis, «  on ne les connaît pas tant que cela ». </p>
<p><b>Jusqu’au déclin</b> présente les immigrants qui pourraient tenter de venir envahir le domaine des survivalistes comme un danger dont il faudrait de protéger. Bien entendu, le fait que les survivalistes se tuent entre eux lors du week end expérimental tempère ces craintes initiales et change complètement la donne. </p>
<p>Certains films donnent des visions plus nuancées. </p>
<p>Dans <b>Jouliks</b>, les <i>gypsies</i> vivant en marge de Toronto sont présentés comme des groupes à part, avec leurs règles, différentes, ce qui conduit à des tensions, surtout pour ceux qui vivent à la marge de chacun des deux groupes, les <i>gypsies</i> et la société régulière, comme c’est le cas dans la petite famille du film. Le regard porté ici est plus nuancé, il implique des gens qui sont dans deux sociétés en même temps, la société d’origine et la société d’accueil. </p>
<p><a href="/fr/post/antigone"><b>Antigone</b></a> propose aussi une vision plus nuancée. S’il est vrai qu’on assiste dans ce film à une importante bavure policière vis-à-vis des groupes composés en partie de nouveaux arrivants, il est vrai aussi que ces derniers ne sont pas des anges non plus, et c’est en partie ce dilemme qui pèse sur <a href="/fr/post/antigone"><b>Antigone</b></a>. </p>

<p>Mais les films québécois des années 2018-2020 que nous avons regardés offrent aussi des images plus traditionnelles du Québec, des thèmes marqués au coin du déclin économique, du misérabilisme et de l’absence du père. On pourrait penser qu’il s’agit d’un biais du choix du Movie Shrink, mais le thème du misérabilisme n’a pas complètement disparu. </p>
<p>Il est difficile de trouver un film plus révélateur du thème du déclin socio-économique que <b>Répertoire des villes disparues</b>. Le titre du film dit tout ce qu’il y a à savoir à cet égard. La famille dans <b>Chiens de garde</b> fait face à leurs difficultés en commettant, pour leur oncle, des actions illégales pour survivre. Dans <b>Jouliks</b>, le jeune père de famille, qui vit de bricoles , et sa femme de prostitution de week-end,  explique à sa fille  que l’on survit en ne payant pas ou en retardant les comptes à payer. Et bien sûr, le héros de <b>La grande noirceur</b>, l’imitateur itinérant de Charlie Chaplin, est l’image même du « petit Québécois » dont les autres abusent facilement. </p>
<p>On disait dans le passé que les films québécois reflétaient souvent l’absence du père. Encore ici, leur présence soulignée ici peut être due au choix du Movie Shrink, mais, quoiqu’il en soit,  on peut dire que , chacun à sa manière, les films Répertoires des villes disparues, <b>Chiens de garde</b>, <b>La grande noirceur</b>, <b>Les nôtres</b> et <a href="/fr/post/antigone"><b>Antigone</b></a> en traitent assez explicitement. </p>

<h1>CONCLUSION</h1>
<p>Les thématiques des films québécois des années 2018-2020, du moins ceux vus par le Movie Shrink, témoignent à la fois de nouveaux thèmes et de plus anciens. À cet égard, nos films reflètent notre situation réelle, faite de changements et de continuité. </p>

    </div>
</div>