backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: 'assets/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/uploads' # The src attribute for uploaded media will begin with /images/uploads
site_url: https://themovieshrink.com
logo_url: https://awake-template.netlify.com/logo-frames/logo-f0.svg

i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: en

collections:
  - name: 'posts' # Used in routes, e.g., /admin/collections/blog
    label: 'Posts' # Used in the UI
    preview_path: '{{slug}}'
    folder: 'content/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., title.md
    i18n: true
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - {
          label: 'Category',
          name: 'category',
          widget: 'relation',
          collection: 'categories',
          searchFields: ['name'],
          valueField: 'name',
          multiple: true,
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'relation',
          collection: 'tags',
          searchFields: ['name'],
          valueField: 'name',
          multiple: true,
          required: false,
        }
      - {
          label: 'Author',
          name: 'author',
          widget: 'string',
          default: 'Jean Mercier',
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Featured Image',
          name: 'featureImage',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Youtube Movie Trailer',
          name: 'youtubeMovieTrailer',
          widget: 'string',
          required: false,
        }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text', required: false, i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
  - name: 'categories'
    label: 'Categories'
    folder: 'content/categories'
    create: true
    slug: '{{slug}}'
    identifier_field: name
    i18n: true
    fields:
      - { label: 'Id', name: 'id', widget: 'string', required: true }
      - { label: 'Name', name: 'name', widget: 'string', i18n: true }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - {
          label: 'Description',
          name: 'description',
          widget: 'markdown',
          required: false,
          i18n: true,
        }
      - {
          label: 'Type',
          name: 'type',
          widget: 'relation',
          collection: 'categoryTypes',
          searchFields: ['name'],
          valueField: 'name',
        }
  - name: 'tags'
    label: 'Tags'
    folder: 'content/tags'
    create: true
    slug: '{{slug}}'
    identifier_field: name,
    i18n: true
    fields:
      - { label: 'Id', name: 'id', widget: 'string', required: true }
      - { label: 'Name', name: 'name', widget: 'string', i18n: true }
      - {
          label: 'Type',
          name: 'type',
          widget: 'relation',
          collection: 'tagTypes',
          searchFields: ['name'],
          valueField: 'name',
        }
  - name: 'categoryTypes'
    label: 'Category Types'
    folder: 'content/categoryTypes'
    create: true
    slug: '{{slug}}'
    identifier_field: name
    i18n: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string', i18n: true }
  - name: 'tagTypes'
    label: 'Tag Types'
    folder: 'content/tagTypes'
    create: true
    slug: '{{slug}}'
    identifier_field: name
    i18n: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string', i18n: true }
